ekf_filter_node:
  ros__parameters:
    
    frequency: 30.0
    sensor_timeout: 0.0
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    publish_acceleration: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: diff_bot_controller/odom
    odom0_config: [
      true, true, false,
      false, false, true,
      false, false, false,
      false, false, false,
      false, false, false]

    imu0: imu_data
    imu0_config: [
      false, true, false,
      false, false, true,
      false, false, false,
      false, false, true,
      false, false, false]
