controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    publish_rate: 30
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_1']
    right_wheel_names: ['right_wheel_1']
    wheel_separation: 0.45
    wheel_radius: 0.15

    use_stamped_vel: false

