controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    diff_controller:
      type: diff_drive_controller/DiffDriveController
    

diff_controller:
  ros__parameters:
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.45
    wheel_radius: 0.15

    use_stamped_vel: false

