controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    diff_bot_controller:
      type: diff_bot_controller/DiffBotController
    

diff_bot_controller:
  ros__parameters:
    num_wheels: 4
    wheel_joint_names: ['Revolute_3', 'Revolute_4', 'Revolute_5', 'Revolute_6']
    wheel_separation: 0.5778 # 0.5778
    wheel_radius: 0.15
    is_reset: false
    publish_rate: 50.0



